### PR TITLE
BPLAT-16037 EPG upload HTTP endpoint documentation

### PR DESCRIPTION
**Pull request by PetriHaikonen**
https://jira.24i.com/browse/BPLAT-16037

### CODE REVIEW

**Comment by PetriHaikonen** [comment]
Marking as WIP as we might need to change the endpoint URLs

**Review by tlangens — COMMENTED** [review]
This belongs in SwaggerHub nowadays.

**Comment by PetriHaikonen** [comment]
> This belongs in SwaggerHub nowadays.

@tlangens I would need to get access then.

**Comment by PetriHaikonen** [comment]
Documentation added to SwaggerHub https://app.swaggerhub.com/apis/24i-API/MetadataUpload/1.0.0

**Pull request closed without merging**
